// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2) {
  return window['go']['main']['App']['AddRule'](arg1, arg2);
}

export function CancelOrganizePreview(arg1) {
  return window['go']['main']['App']['CancelOrganizePreview'](arg1);
}

export function CancelScan(arg1) {
  return window['go']['main']['App']['CancelScan'](arg1);
}

export function CancelSearch(arg1) {
  return window['go']['main']['App']['CancelSearch'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function ListRules() {
  return window['go']['main']['App']['ListRules']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function StartOrganizePreview(arg1) {
  return window['go']['main']['App']['StartOrganizePreview'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StartSearch(arg1, arg2) {
  return window['go']['main']['App']['StartSearch'](arg1, arg2);
}
