/**
 * Mirrors the JSON payloads emitted by the Go backend in
 * app_duplicates.go and internal/duplicates/types.go. Event payloads
 * aren't generated by Wails, so — consistent with scanTypes.ts,
 * searchTypes.ts, and ruleTypes.ts — these are kept in sync by hand.
 */

export type DuplicatePhase = 'scanning' | 'hashing'

export interface DuplicateProgress {
  phase: DuplicatePhase
  filesScanned: number
  filesHashed: number
  currentPath: string
}

export interface DuplicateFile {
  path: string
  modTime: string
}

export interface DuplicateGroup {
  hash: string
  size: number
  files: DuplicateFile[]
}

export interface DuplicateIssue {
  path: string
  error: string
}

export interface DuplicateResult {
  root: string
  filesScanned: number
  filesHashed: number
  groups: DuplicateGroup[]
  totalReclaimable: number
  truncated: boolean
  issues: DuplicateIssue[]
  cancelled: boolean
  durationNs: number
}

export interface DuplicateProgressEvent extends DuplicateProgress {
  id: string
}

export interface DuplicateCompletedEvent extends DuplicateResult {
  id: string
}

export interface DuplicateFailedEvent {
  id: string
  error: string
}

export const DUPLICATE_EVENTS = {
  started: 'duplicates.started',
  progress: 'duplicates.progress',
  completed: 'duplicates.completed',
  cancelled: 'duplicates.cancelled',
  failed: 'duplicates.failed',
} as const
