/**
 * Mirrors the JSON payloads emitted by the Go backend in
 * app_operations.go and internal/operations/types.go. Event payloads
 * aren't generated by Wails, so — consistent with the rest of lib/ —
 * these are kept in sync by hand.
 */

export type ConflictPolicy = 'skip' | 'keep_both' | 'replace'

export interface MoveRequestItem {
  source: string
  destination: string
}

export interface OperationProgress {
  completed: number
  total: number
  currentPath: string
}

export type OperationOutcome = 'moved' | 'skipped' | 'failed'

export interface OperationItemResult {
  source: string
  destination: string
  outcome: OperationOutcome
  error?: string
}

export interface ApplyResult {
  batchId: string
  items: OperationItemResult[]
  succeeded: number
  skipped: number
  failed: number
  cancelled: boolean
  durationNs: number
}

export interface UndoItemResult {
  source: string
  destination: string
  outcome: OperationOutcome
  error?: string
}

export interface UndoResult {
  batchId: string
  items: UndoItemResult[]
  restored: number
  skipped: number
  failed: number
}

export interface ApplyProgressEvent extends OperationProgress {
  id: string
}

export interface ApplyCompletedEvent extends ApplyResult {
  id: string
}

export interface ApplyFailedEvent {
  id: string
  error: string
}

export const APPLY_EVENTS = {
  started: 'operations.apply.started',
  progress: 'operations.apply.progress',
  completed: 'operations.apply.completed',
  cancelled: 'operations.apply.cancelled',
  failed: 'operations.apply.failed',
} as const
